"use client";import { useEffect,useState } from "react";import { toast } from "sonner";import { Button } from "@/components/ui/button";import { Input } from "@/components/ui/input";import { emptyWeek,validateWeeklyPattern,type WeekPattern } from "@/lib/schedule/rules";
const days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
export function WeeklyGrid(){const [week,setWeek]=useState<WeekPattern>(emptyWeek());const [revision,setRevision]=useState(0);const [loading,setLoading]=useState(true);const [pending,setPending]=useState(false);
useEffect(()=>{fetch("/api/schedule").then(response=>response.json()).then((data:any)=>{if(data.week){setWeek(data.week);setRevision(data.revision);}setLoading(false);}).catch(()=>setLoading(false));},[]);
function patch(index:number,changes:Partial<WeekPattern[number]>){setWeek(current=>current.map((day,i)=>i===index?{...day,...changes}:day) as WeekPattern);}
async function save(){const validation=validateWeeklyPattern(week);if(!validation.valid){toast.error(validation.errors[0]);return;}setPending(true);try{const response=await fetch("/api/schedule",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({week,expectedRevision:revision})});const data:any=await response.json();if(!response.ok)throw new Error(data.error);setRevision(data.revision);toast.success("Weekly schedule saved");}catch(issue){toast.error(issue instanceof Error?issue.message:"Unable to save schedule");}finally{setPending(false);}}
return <div className="max-w-5xl"><p className="text-sm font-medium text-primary">YOUR WORK WEEK</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em]">Schedule</h1><p className="mt-3 max-w-2xl text-muted-foreground">Set a repeating Sunday–Saturday pattern in Cairo time. Changes will appear in future weeks until you update it.</p><div className="mt-9 border-t border-border">{loading?<div className="py-10 text-muted-foreground">Loading your schedule…</div>:week.map((day,index)=><div key={days[index]} className="grid gap-3 border-b border-border py-5 sm:grid-cols-[140px_90px_1fr_1fr] sm:items-center"><strong>{days[index]}</strong><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!day.off} onChange={event=>patch(index,{off:!event.target.checked,breaks:[],lunch:null})} />Working</label>{!day.off&&<><div className="flex items-center gap-2"><span className="text-sm text-muted-foreground">From</span><Input aria-label={days[index]+" start"} type="time" value={day.start} onChange={event=>patch(index,{start:event.target.value})} /></div><div className="flex items-center gap-2"><span className="text-sm text-muted-foreground">To</span><Input aria-label={days[index]+" end"} type="time" value={day.end} onChange={event=>patch(index,{end:event.target.value})} /></div></>}</div>)}</div><div className="mt-6 flex justify-end"><Button onClick={save} disabled={pending||loading} className="min-w-[140px]">{pending?"Saving…":"Save schedule"}</Button></div><p className="mt-4 text-sm text-muted-foreground">Breaks, lunch and one-day exceptions are coming into this editor next.</p></div>;
}

