import { bindings } from "./runtime";import { decryptCustomerValue,encryptCustomerValue } from "./crypto";import { getFollowUp } from "./follow-ups";import { getRccHandoff } from "./rcc";import { statusForSource,validateCase } from "../cases/rules";import type { CaseRecord,CaseStatus,SaveCaseInput } from "../cases/types";
type Row={id:string;human_id:string;owner_user_id:string;customer_encrypted:string;account_encrypted:string;summary_encrypted:string;category:string;priority:"High"|"Medium"|"Low";status:CaseStatus;source_type:string;source_id:string|null;revision:number;created_at:string;updated_at:string};
const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function humanId(){const bytes=crypto.getRandomValues(new Uint8Array(8));return "MND-"+Array.from(bytes,b=>alphabet[b%alphabet.length]).join("");}
async function decode(row:Row):Promise<CaseRecord>{return {id:row.id,humanId:row.human_id,ownerUserId:row.owner_user_id,customerName:await decryptCustomerValue(row.customer_encrypted),accountNumber:await decryptCustomerValue(row.account_encrypted),summary:await decryptCustomerValue(row.summary_encrypted),category:row.category,priority:row.priority,status:row.status,sourceType:row.source_type,sourceId:row.source_id,revision:row.revision,createdAt:row.created_at,updatedAt:row.updated_at};}
export async function getCase(ownerUserId:string,id:string){const row=await bindings().DB.prepare("SELECT * FROM cases WHERE id=? AND owner_user_id=?").bind(id,ownerUserId).first<Row>();return row?decode(row):null;}
export async function createCaseFromWorkflow(ownerUserId:string,input:SaveCaseInput):Promise<CaseRecord>{validateCase(input);let snapshot:any={};if(input.source.type==="follow-up"){const source=await getFollowUp(ownerUserId,input.source.id);if(!source)throw new Error("SOURCE_NOT_FOUND");input.source.status=source.status;snapshot={reason:source.reason,dueAt:source.dueAt,status:source.status};}else if(input.source.type==="rcc-handoff"){const source=await getRccHandoff(ownerUserId,input.source.id);if(!source)throw new Error("SOURCE_NOT_FOUND");snapshot={workflow:source.workflow,status:"prepared",subject:source.draft.subject};}
const id=crypto.randomUUID(),status=statusForSource(input.source),db=bindings().DB;for(let attempt=0;attempt<5;attempt++){try{const code=humanId();await db.batch([db.prepare("INSERT INTO cases (id,human_id,owner_user_id,customer_encrypted,account_encrypted,summary_encrypted,category,priority,status,source_type,source_id,snapshot_encrypted) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,code,ownerUserId,await encryptCustomerValue(input.customerName.trim()),await encryptCustomerValue(input.accountNumber.trim()),await encryptCustomerValue(input.summary.trim()),input.category,input.priority,status,input.source.type,"id" in input.source?input.source.id:null,await encryptCustomerValue(JSON.stringify(snapshot))),db.prepare("INSERT INTO case_events (id,case_id,owner_user_id,event_type,payload_encrypted) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),id,ownerUserId,"created",await encryptCustomerValue(JSON.stringify({status,source:input.source.type})))]);return (await getCase(ownerUserId,id))!;}catch(error){if(!(error instanceof Error)||!error.message.includes("UNIQUE"))throw error;}}throw new Error("CASE_ID_COLLISION");}
export async function listCases(ownerUserId:string,query?:{search?:string;status?:CaseStatus;limit?:number;cursor?:string}){
 const db=bindings().DB,limit=Math.min(100,Math.max(1,query?.limit??50)),needle=query?.search?.trim().toLowerCase();
 const status=query?.status??null;
 let offset=/^\d{1,9}$/u.test(query?.cursor??"")?Number(query?.cursor):0;
 const items:CaseRecord[]=[];
 while(items.length<limit){
  const rows=await db.prepare("SELECT * FROM cases WHERE owner_user_id=? AND (? IS NULL OR status=?) ORDER BY updated_at DESC,id DESC LIMIT 100 OFFSET ?").bind(ownerUserId,status,status,offset).all<Row>();
  if(!rows.results.length)break;
  for(const row of rows.results){offset++;const item=await decode(row);if(!needle||[item.humanId,item.customerName,item.accountNumber,item.summary].some(value=>value.toLowerCase().includes(needle)))items.push(item);if(items.length===limit)break;}
  if(rows.results.length<100)break;
 }
 const count=await db.prepare("SELECT count(*) AS total FROM cases WHERE owner_user_id=? AND (? IS NULL OR status=?)").bind(ownerUserId,status,status).first<{total:number}>();
 return {items,nextCursor:offset<(count?.total??0)?String(offset):null};
}
export async function setCaseStatus(ownerUserId:string,id:string,status:CaseStatus,expectedRevision:number){const current=await getCase(ownerUserId,id);if(!current)return null;if(current.revision!==expectedRevision)throw new Error("STALE_REVISION");const db=bindings().DB;const results=await db.batch([db.prepare("UPDATE cases SET status=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND owner_user_id=? AND revision=?").bind(status,id,ownerUserId,expectedRevision),db.prepare("INSERT INTO case_events (id,case_id,owner_user_id,event_type,payload_encrypted) SELECT ?,?,?,?,? WHERE changes()=1").bind(crypto.randomUUID(),id,ownerUserId,"status_changed",await encryptCustomerValue(JSON.stringify({from:current.status,to:status})))]);if(results[0].meta.changes!==1)throw new Error("STALE_REVISION");return getCase(ownerUserId,id);}
export async function caseHistory(ownerUserId:string,id:string){if(!await getCase(ownerUserId,id))return null;const rows=await bindings().DB.prepare("SELECT id,event_type,payload_encrypted,created_at FROM case_events WHERE owner_user_id=? AND case_id=? ORDER BY created_at DESC").bind(ownerUserId,id).all<{id:string;event_type:string;payload_encrypted:string;created_at:string}>();return Promise.all(rows.results.map(async row=>({id:row.id,type:row.event_type,payload:JSON.parse(await decryptCustomerValue(row.payload_encrypted)),createdAt:row.created_at})));}
export async function deleteCase(ownerUserId:string,id:string,expectedRevision:number){const result=await bindings().DB.prepare("DELETE FROM cases WHERE owner_user_id=? AND id=? AND revision=?").bind(ownerUserId,id,expectedRevision).run();if((result.meta.changes??0)>0)return true;const exists=await getCase(ownerUserId,id);if(exists)throw new Error("STALE_REVISION");return false;}
