import { bindings } from "./runtime";
import { decryptCustomerValue, encryptCustomerValue } from "./crypto";
import { transitionFollowUp } from "../follow-ups/rules";
import type { FollowUp, FollowUpCommand } from "../follow-ups/types";

type Row={id:string;owner_user_id:string;account_number:string;phone_number:string;customer_name:string;notes:string;reason_code:string;scheduled_at_utc:string;source_timezone:"Africa/Cairo"|"America/New_York";status:FollowUp["status"];attempt_count:number;voicemail_required:number;voicemail_left:number;priority:"normal"|"urgent";completed_at:string|null;revision:number};
export type NewFollowUp={customerName:string;accountNumber:string;phoneNumber:string;reason:string;priority:"normal"|"urgent";dueAt:string;sourceTimezone:"Africa/Cairo"|"America/New_York";notes?:string};
async function decode(row:Row):Promise<FollowUp>{return {id:row.id,ownerUserId:row.owner_user_id,customerName:await decryptCustomerValue(row.customer_name),accountNumber:await decryptCustomerValue(row.account_number),phoneNumber:await decryptCustomerValue(row.phone_number),notes:row.notes?await decryptCustomerValue(row.notes):"",reason:row.reason_code,priority:row.priority,dueAt:row.scheduled_at_utc,sourceTimezone:row.source_timezone,status:row.status,attemptCount:row.attempt_count,voicemailRequired:Boolean(row.voicemail_required),voicemailLeft:Boolean(row.voicemail_left),completedAt:row.completed_at,revision:row.revision};}
function validate(input:NewFollowUp){if(!input.customerName.trim()||!input.accountNumber.trim()||!input.phoneNumber.trim()||!input.reason.trim())throw new Error("Required follow-up details are missing");if(!Number.isFinite(Date.parse(input.dueAt))||Date.parse(input.dueAt)<=Date.now())throw new Error("Due time must be in the future");}
export async function createFollowUp(ownerUserId:string,input:NewFollowUp):Promise<FollowUp>{validate(input);const db=bindings().DB;const id=crypto.randomUUID();await db.batch([
 db.prepare("INSERT INTO callbacks (id,owner_user_id,account_number,phone_number,customer_name,notes,reason_code,scheduled_at_utc,source_timezone,status,priority,revision) VALUES (?,?,?,?,?,?,?,?,?,'pending',?,1)").bind(id,ownerUserId,await encryptCustomerValue(input.accountNumber.trim()),await encryptCustomerValue(input.phoneNumber.trim()),await encryptCustomerValue(input.customerName.trim()),input.notes?await encryptCustomerValue(input.notes):"",input.reason,input.dueAt,input.sourceTimezone,input.priority),
 db.prepare("INSERT INTO callback_events (id,callback_id,owner_user_id,actor_user_id,event_type,new_value_json) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),id,ownerUserId,ownerUserId,"created",await encryptCustomerValue(JSON.stringify({summary:"Follow-up created"})))
]);return (await getFollowUp(ownerUserId,id))!;}
export async function getFollowUp(ownerUserId:string,id:string){const row=await bindings().DB.prepare("SELECT * FROM callbacks WHERE id = ? AND owner_user_id = ?").bind(id,ownerUserId).first<Row>();return row?decode(row):null;}
export async function listFollowUps(ownerUserId:string,query?:{search?:string;limit?:number;cursor?:string}){const limit=Math.min(100,Math.max(1,query?.limit??50));const rows=await bindings().DB.prepare("SELECT * FROM callbacks WHERE owner_user_id = ? ORDER BY scheduled_at_utc ASC LIMIT 500").bind(ownerUserId).all<Row>();let decoded=await Promise.all(rows.results.map(decode));const search=query?.search?.trim().toLowerCase();if(search)decoded=decoded.filter(item=>[item.customerName,item.accountNumber,item.phoneNumber,item.reason,item.notes].some(value=>value.toLowerCase().includes(search)));return {items:decoded.slice(0,limit),nextCursor:null};}
export async function applyFollowUpCommand(ownerUserId:string,id:string,command:FollowUpCommand,expectedRevision:number){const current=await getFollowUp(ownerUserId,id);if(!current)return null;if(current.revision!==expectedRevision)throw new Error("STALE_REVISION");const {next,event}=transitionFollowUp(current,command,new Date());const db=bindings().DB;const result=await db.prepare("UPDATE callbacks SET status=?,scheduled_at_utc=?,attempt_count=?,voicemail_required=?,voicemail_left=?,completed_at=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND owner_user_id=? AND revision=?").bind(next.status,next.dueAt,next.attemptCount,next.voicemailRequired?1:0,next.voicemailLeft?1:0,next.completedAt,id,ownerUserId,expectedRevision).run();if(result.meta.changes!==1)throw new Error("STALE_REVISION");await db.prepare("INSERT INTO callback_events (id,callback_id,owner_user_id,actor_user_id,event_type,new_value_json) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),id,ownerUserId,ownerUserId,event.type,await encryptCustomerValue(JSON.stringify(event))).run();return next;}
export async function followUpHistory(ownerUserId:string,id:string){if(!await getFollowUp(ownerUserId,id))return null;const rows=await bindings().DB.prepare("SELECT id,event_type,new_value_json,created_at FROM callback_events WHERE owner_user_id=? AND callback_id=? ORDER BY created_at DESC").bind(ownerUserId,id).all<{id:string;event_type:string;new_value_json:string;created_at:string}>();return Promise.all(rows.results.map(async row=>({id:row.id,type:row.event_type,payload:row.new_value_json?JSON.parse(await decryptCustomerValue(row.new_value_json)):null,createdAt:row.created_at})));}
export async function saveFollowUpDraft(ownerUserId:string,input:unknown,expectedRevision?:number){const db=bindings().DB;const existing=await db.prepare("SELECT revision FROM follow_up_drafts WHERE owner_user_id=?").bind(ownerUserId).first<{revision:number}>();if(existing&&existing.revision!==expectedRevision)throw new Error("STALE_REVISION");if(!existing&&expectedRevision&&expectedRevision!==0)throw new Error("STALE_REVISION");const payload=await encryptCustomerValue(JSON.stringify(input));if(existing){await db.prepare("UPDATE follow_up_drafts SET payload_encrypted=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE owner_user_id=? AND revision=?").bind(payload,ownerUserId,existing.revision).run();return existing.revision+1;}await db.prepare("INSERT INTO follow_up_drafts (owner_user_id,payload_encrypted,revision) VALUES (?,?,1)").bind(ownerUserId,payload).run();return 1;}
export async function getFollowUpDraft(ownerUserId:string){const row=await bindings().DB.prepare("SELECT payload_encrypted,revision FROM follow_up_drafts WHERE owner_user_id=?").bind(ownerUserId).first<{payload_encrypted:string;revision:number}>();return row?{payload:JSON.parse(await decryptCustomerValue(row.payload_encrypted)),revision:row.revision}:null;}
