import { z } from "zod";
import { requireWorkspaceSession } from "@/lib/server/auth";
import { applyFollowUpCommand, editFollowUpProfile, followUpHistory, getFollowUp } from "@/lib/server/follow-ups";
import { followUpProfileSchema } from "@/lib/follow-ups/schema";
import { errorJson, json, parseJson, requireSameOrigin } from "@/lib/server/http";
const schema=z.object({expectedRevision:z.number().int().positive(),command:z.object({type:z.enum(["busy","no_answer","confirm_voicemail","follow_up","escalation_required","resolved","wrong_number","cancel","restore","reschedule"]),dueAt:z.string().datetime().optional(),voicemailLeft:z.boolean().optional()}).strict()}).strict();
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const user=await requireWorkspaceSession(request);if(!user)return errorJson(401,"Authentication required");const {id}=await params;const item=await getFollowUp(user.id,id);if(!item)return errorJson(404,"Follow-up not found");return json({item,history:await followUpHistory(user.id,id)});}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{requireSameOrigin(request);const user=await requireWorkspaceSession(request);if(!user)return errorJson(401,"Authentication required");const {id}=await params;const input=await parseJson(request,schema);const item=await applyFollowUpCommand(user.id,id,input.command,input.expectedRevision);if(!item)return errorJson(404,"Follow-up not found");return json({item});}catch(error){if(error instanceof Error&&error.message==="STALE_REVISION")return errorJson(409,"This follow-up changed. Refresh and try again.");return errorJson(400,error instanceof Error?error.message:"Unable to update follow-up");}}
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){try{requireSameOrigin(request);const user=await requireWorkspaceSession(request);if(!user)return errorJson(401,"Authentication required");const {id}=await params;const input=await parseJson(request,z.object({expectedRevision:z.number().int().positive(),profile:followUpProfileSchema}).strict());const item=await editFollowUpProfile(user.id,id,input.profile,input.expectedRevision);if(!item)return errorJson(404,"Follow-up not found");return json({item});}catch(error){if(error instanceof Error&&error.message==="STALE_REVISION")return errorJson(409,"This follow-up changed. Refresh and try again.");return errorJson(400,error instanceof Error?error.message:"Unable to edit follow-up");}}
