"use client";
import Link from "next/link";import { FormEvent,useState } from "react";import { useRouter } from "next/navigation";import { ArrowLeft } from "lucide-react";import { toast } from "sonner";
import { wallTimeToUtc } from "@/lib/follow-ups/time";import { Button } from "@/components/ui/button";import { Input } from "@/components/ui/input";import { Label } from "@/components/ui/label";import { Textarea } from "@/components/ui/textarea";
const reasons=["Customer requested callback","Call disconnected","Waiting for reboot/reset","Make sure technician arrived","Technician missed appointment window","Technician go-back request","Make sure service is stable","Check appointment status","Check escalation/update","Verify issue resolution","Continue troubleshooting","Waiting for information","Other"];
export function FollowUpForm(){const router=useRouter();const [zone,setZone]=useState<"Africa/Cairo"|"America/New_York">("Africa/Cairo");const [pending,setPending]=useState(false);const [error,setError]=useState("");
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;setPending(true);setError("");const form=new FormData(event.currentTarget);try{const dueAt=wallTimeToUtc(String(form.get("dueAt")),zone);const input={customerName:form.get("customerName"),accountNumber:form.get("accountNumber"),phoneNumber:form.get("phoneNumber"),reason:form.get("reason"),priority:form.get("priority"),dueAt,sourceTimezone:zone,notes:form.get("notes")};const response=await fetch("/api/follow-ups",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});const data:any=await response.json();if(!response.ok)throw new Error(data.error??"Unable to create follow-up");toast.success("Follow-up scheduled");router.push("/follow-ups");router.refresh();}catch(issue){setError(issue instanceof Error?issue.message:"Unable to create follow-up");}finally{setPending(false);}}
return <div className="mx-auto max-w-[800px]"><Link href="/follow-ups" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Follow-ups</Link><p className="mt-8 text-sm font-medium text-primary">NEW FOLLOW-UP</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em]">Keep your promise.</h1><p className="mt-3 text-muted-foreground">Capture what to call about and when. The queue will bring it back at the right time.</p><form onSubmit={submit} className="mt-9 space-y-8"><section className="grid gap-5 border-t border-border pt-7 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="customerName">Customer name</Label><Input id="customerName" name="customerName" required /></div><div className="space-y-2"><Label htmlFor="accountNumber">Account number</Label><Input id="accountNumber" name="accountNumber" required /></div><div className="space-y-2"><Label htmlFor="phoneNumber">Phone number</Label><Input id="phoneNumber" name="phoneNumber" type="tel" required /></div><div className="space-y-2"><Label htmlFor="reason">Reason</Label><select id="reason" name="reason" required className="flex h-9 w-full rounded-md border border-input bg-background px-3 text-sm">{reasons.map(reason=><option key={reason}>{reason}</option>)}</select></div><div className="space-y-2"><Label htmlFor="dueAt">Call back at</Label><Input id="dueAt" name="dueAt" type="datetime-local" required /></div><div className="space-y-2"><Label htmlFor="zone">Time zone</Label><select id="zone" value={zone} onChange={event=>setZone(event.target.value as typeof zone)} className="flex h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="Africa/Cairo">Cairo time</option><option value="America/New_York">New York time</option></select></div><div className="space-y-2"><Label htmlFor="priority">Priority</Label><select id="priority" name="priority" className="flex h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="normal">Normal</option><option value="urgent">Urgent</option></select></div></section><div className="space-y-2 border-t border-border pt-7"><Label htmlFor="notes">Context and next step</Label><Textarea id="notes" name="notes" rows={5} placeholder="What should you know when it is time to call?" /></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-3 border-t border-border pt-6"><Button variant="outline" type="button" asChild><Link href="/follow-ups">Cancel</Link></Button><Button type="submit" className="min-w-[160px]" disabled={pending}>{pending?"Scheduling…":"Schedule follow-up"}</Button></div></form></div>;
}

