"use client";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
type User={id:string;username:string;displayName:string;role:"user"|"admin";status:"active"|"disabled";mustChangePassword:boolean};
export function AdminUsers(){const [users,setUsers]=useState<User[]>([]);const [pending,setPending]=useState(false);const [error,setError]=useState("");
async function refresh(){const response=await fetch("/api/admin/users");if(response.ok)setUsers(((await response.json()) as any).users);}
useEffect(()=>{void refresh();},[]);
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:form.get("username"),displayName:form.get("displayName"),temporaryPassword:form.get("temporaryPassword")})});const data:any=await response.json();if(!response.ok)throw new Error(data.error);(event.target as HTMLFormElement).reset();toast.success("Agent created. Share the temporary password securely.");await refresh();}catch(issue){setError(issue instanceof Error?issue.message:"Unable to create agent");}finally{setPending(false);}}
async function disable(user:User){if(!window.confirm(`Disable ${user.displayName}? Their active sessions will end.`))return;const response=await fetch(`/api/admin/users/${user.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"disable"})});if(response.ok){toast.success("Agent disabled");await refresh();}else toast.error("Unable to disable agent");}
return <div className="max-w-5xl"><p className="text-sm font-medium text-primary">ADMINISTRATION</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em]">Agent accounts</h1><p className="mt-3 text-muted-foreground">Create individual accounts. Each agent’s work stays private.</p><div className="mt-9 grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><section><h2 className="text-lg font-semibold">Agents</h2><div className="mt-4 divide-y divide-border border-y border-border">{users.map(user=><div key={user.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-medium">{user.displayName}</p><p className="text-sm text-muted-foreground">@{user.username} · {user.role} · {user.status}</p></div>{user.role==="user"&&user.status==="active"&&<Button variant="outline" size="sm" onClick={()=>disable(user)}>Disable</Button>}</div>)}{users.length===0&&<p className="py-8 text-sm text-muted-foreground">No agents yet.</p>}</div></section><section className="rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Create agent</h2><form onSubmit={submit} className="mt-5 space-y-4"><div className="space-y-2"><Label htmlFor="agent-name">Display name</Label><Input id="agent-name" name="displayName" required /></div><div className="space-y-2"><Label htmlFor="agent-username">Username</Label><Input id="agent-username" name="username" minLength={3} required /></div><div className="space-y-2"><Label htmlFor="agent-password">Temporary password</Label><Input id="agent-password" name="temporaryPassword" type="password" minLength={12} required /></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button className="w-full" disabled={pending}>{pending?"Creating…":"Create agent"}</Button></form></section></div></div>}

