export const TRI_STATE_OPTIONS = [
  { value: 'yes', label: 'Yes' },
  { value: 'no', label: 'No' },
  { value: 'unknown', label: 'Unknown' },
];

export const SLA_DURATION_OPTIONS = [
  { value: '', label: 'Not selected' },
  { value: '24-hours', label: '24 hours', emailLabel: '24-hour' },
  { value: '48-hours', label: '48 hours', emailLabel: '48-hour' },
  { value: '72-hours', label: '72 hours', emailLabel: '72-hour' },
  { value: '30-days', label: '30 days', emailLabel: '30-day' },
  { value: '45-days', label: '45 days', emailLabel: '45-day' },
  { value: 'custom', label: 'Custom SLA' },
];

export const QUESTIONS = [
  {
    id: 'customerArrived',
    source: 'customer',
    label: 'Did the technician physically arrive?',
    type: 'choice',
    options: TRI_STATE_OPTIONS,
  },
  {
    id: 'contactReceived',
    source: 'customer',
    label: 'Did the customer receive a call, voicemail, or message?',
    type: 'choice',
    options: TRI_STATE_OPTIONS,
  },
  {
    id: 'customerAvailable',
    source: 'customer',
    label: 'Was the customer available during the appointment window?',
    type: 'choice',
    options: TRI_STATE_OPTIONS,
  },
  {
    id: 'workAttempted',
    source: 'customer',
    label: 'Was any work attempted?',
    type: 'choice',
    options: TRI_STATE_OPTIONS,
  },
  {
    id: 'workCompleted',
    source: 'customer',
    label: 'Was any work completed?',
    type: 'choice',
    options: TRI_STATE_OPTIONS,
  },
  {
    id: 'customerInstructions',
    source: 'customer',
    label: 'What was the customer instructed to do?',
    type: 'textarea',
    placeholder: 'Capture the customer’s account of the instructions.',
  },
  {
    id: 'instructionType',
    source: 'customer',
    label: 'What type of instruction was reported?',
    type: 'select',
    options: [
      { value: '', label: 'Not answered' },
      { value: 'contact-support', label: 'Contact support' },
      { value: 'reschedule', label: 'Reschedule another appointment' },
      { value: 'wait-follow-up', label: 'Wait for follow-up' },
      { value: 'other-department', label: 'Contact another department' },
      { value: 'no-instruction', label: 'No instruction reported' },
      { value: 'other', label: 'Other instruction' },
      { value: 'unknown', label: 'Unknown' },
    ],
  },
  {
    id: 'instructionDelivery',
    source: 'customer',
    label: 'How was the instruction reportedly delivered?',
    type: 'select',
    options: [
      { value: '', label: 'Not answered' },
      { value: 'in-person', label: 'In person' },
      { value: 'phone', label: 'Telephone call' },
      { value: 'voicemail', label: 'Voicemail' },
      { value: 'written', label: 'Text or written message' },
      { value: 'door-notice', label: 'Door notice' },
      { value: 'other-person', label: 'Through another person' },
      { value: 'unknown', label: 'Unknown' },
    ],
  },
  {
    id: 'reasonProvided',
    source: 'customer',
    label: 'What reason was provided?',
    type: 'textarea',
    placeholder: 'Use the customer’s wording where practical.',
  },
  {
    id: 'customerAdditional',
    source: 'customer',
    label: 'Additional customer account',
    type: 'textarea',
    placeholder: 'Add any other customer-reported visit detail.',
  },
  {
    id: 'slaDuration',
    source: 'customer',
    label: 'Promised SLA',
    type: 'select',
    options: SLA_DURATION_OPTIONS,
  },
  {
    id: 'customSlaDuration',
    source: 'customer',
    label: 'Custom SLA duration',
    type: 'text',
    placeholder: 'Example: 10 business days',
    showWhen: { questionId: 'slaDuration', value: 'custom' },
  },
  {
    id: 'slaCommunicatedAt',
    source: 'customer',
    label: 'When was the SLA communicated?',
    type: 'text',
    placeholder: 'Optional date and time',
  },
  {
    id: 'slaReference',
    source: 'customer',
    label: 'Related case or reference',
    type: 'text',
    placeholder: 'Optional case, ticket, or work-order number',
  },
  {
    id: 'slaDueAt',
    source: 'customer',
    label: 'When did the SLA expire?',
    type: 'text',
    placeholder: 'Optional due or expired date and time',
  },
  {
    id: 'slaLastStatus',
    source: 'customer',
    label: 'Last known status',
    type: 'textarea',
    placeholder: 'Optional — capture the last status shown or communicated.',
  },
  {
    id: 'visitStatus',
    source: 'records',
    label: 'Visit status',
    type: 'select',
    options: [
      { value: '', label: 'Not checked' },
      { value: 'scheduled', label: 'Scheduled' },
      { value: 'in-progress', label: 'In progress' },
      { value: 'completed', label: 'Completed' },
      { value: 'cancelled', label: 'Cancelled' },
      { value: 'missed', label: 'Missed' },
      { value: 'unknown', label: 'Unknown' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'arrivalStatus',
    source: 'records',
    label: 'Arrival status',
    type: 'select',
    options: [
      { value: '', label: 'Not checked' },
      { value: 'not-arrived', label: 'Not arrived' },
      { value: 'en-route', label: 'En route' },
      { value: 'arrived', label: 'Arrived' },
      { value: 'completed', label: 'Arrival and completion recorded' },
      { value: 'unknown', label: 'Unknown' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'arrivalTime',
    source: 'records',
    label: 'Recorded arrival time',
    type: 'text',
    placeholder: 'Optional exact timestamp',
  },
  {
    id: 'contactAttempt',
    source: 'records',
    label: 'Contact attempt',
    type: 'select',
    options: [
      { value: '', label: 'Not checked' },
      { value: 'none-recorded', label: 'None recorded' },
      { value: 'attempted', label: 'Attempt recorded' },
      { value: 'connected', label: 'Contact completed' },
      { value: 'unknown', label: 'Unknown' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'contactTime',
    source: 'records',
    label: 'Recorded contact time',
    type: 'text',
    placeholder: 'Optional exact timestamp',
  },
  {
    id: 'completionStatus',
    source: 'records',
    label: 'Completion status',
    type: 'select',
    options: [
      { value: '', label: 'Not checked' },
      { value: 'not-started', label: 'Not started' },
      { value: 'incomplete', label: 'Incomplete' },
      { value: 'completed', label: 'Completed' },
      { value: 'unknown', label: 'Unknown' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'technicianNotes',
    source: 'records',
    label: 'Technician notes',
    type: 'textarea',
    placeholder: 'Paste or summarize the available technician notes.',
  },
  {
    id: 'dispatchNotes',
    source: 'records',
    label: 'Dispatch notes',
    type: 'textarea',
    placeholder: 'Paste or summarize relevant dispatch information.',
  },
  {
    id: 'otherInternalInfo',
    source: 'records',
    label: 'Other internal information',
    type: 'textarea',
    placeholder: 'Add any other available system information.',
  },
];

export const QUESTION_BY_ID = Object.fromEntries(QUESTIONS.map((question) => [question.id, question]));

export function isQuestionVisible(question, answers = {}) {
  if (!question?.showWhen) return true;
  return answers[question.showWhen.questionId] === question.showWhen.value;
}

export const IMPACTS = [
  { id: 'service-unresolved', label: 'Service remains unresolved' },
  { id: 'redirected-support', label: 'Customer was redirected to support' },
  { id: 'new-appointment', label: 'Another appointment may be required' },
  { id: 'waited-window', label: 'Customer waited through the appointment window' },
  { id: 'repeat-troubleshooting', label: 'Customer must repeat troubleshooting' },
  { id: 'repeated-failed-visits', label: 'Multiple failed visits' },
  { id: 'escalation-requested', label: 'Customer requested escalation' },
  { id: 'cancellation-risk', label: 'Cancellation risk' },
  { id: 'accessibility-safety', label: 'Accessibility or safety concern' },
  { id: 'dissatisfaction', label: 'Customer expressed dissatisfaction' },
  { id: 'other', label: 'Other impact' },
];

export const IMPACT_BY_ID = Object.fromEntries(IMPACTS.map((impact) => [impact.id, impact]));

export const REQUESTED_OUTCOMES = [
  { id: 'review-visit-handling', label: 'Review visit handling', kind: 'primary' },
  { id: 'verify-arrival', label: 'Verify arrival activity', kind: 'primary' },
  { id: 'verify-contact', label: 'Verify contact activity', kind: 'primary' },
  { id: 'review-instructions', label: 'Review instructions provided to the customer', kind: 'primary' },
  { id: 'review-incomplete-work', label: 'Review why work was not completed', kind: 'primary' },
  { id: 'correct-status', label: 'Correct the visit status where appropriate', kind: 'primary' },
  { id: 'review-sla-status', label: 'Review expired SLA and current status', kind: 'primary' },
  { id: 'restore-appointment', label: 'Restore or arrange the appointment', kind: 'recovery' },
  { id: 'earliest-resolution', label: 'Assist with the earliest appropriate resolution', kind: 'recovery' },
  { id: 'advise-next-action', label: 'Advise on the correct next action', kind: 'recovery' },
  { id: 'provide-status-resolution', label: 'Provide status and appropriate resolution', kind: 'recovery' },
];

export const REQUESTED_OUTCOME_BY_ID = Object.fromEntries(
  REQUESTED_OUTCOMES.map((outcome) => [outcome.id, outcome]),
);

export const SITUATIONS = [
  {
    id: 'did-not-arrive',
    group: 'Arrival',
    label: 'Technician did not arrive',
    questionIds: ['customerArrived', 'contactReceived', 'customerAvailable', 'visitStatus', 'arrivalStatus', 'arrivalTime', 'contactAttempt', 'contactTime', 'technicianNotes', 'dispatchNotes'],
    essentialFacts: ['customerArrived', 'contactReceived', 'customerAvailable'],
    recommendedFacts: ['visitStatus', 'arrivalStatus', 'contactAttempt', 'technicianNotes'],
    impactIds: ['service-unresolved', 'waited-window', 'new-appointment', 'repeated-failed-visits', 'escalation-requested', 'cancellation-risk', 'accessibility-safety', 'dissatisfaction'],
    contradictionRules: ['arrival-mismatch', 'contact-mismatch'],
    emailSentenceIntents: ['customer-arrival', 'customer-contact', 'record-arrival', 'record-contact'],
    reviewAreas: ['arrival activity', 'contact attempts', 'appointment handling', 'technician notes', 'dispatch notes'],
  },
  {
    id: 'arrival-disputed',
    group: 'Arrival',
    label: 'Arrival status is disputed',
    questionIds: ['customerArrived', 'contactReceived', 'customerAvailable', 'visitStatus', 'arrivalStatus', 'arrivalTime', 'contactAttempt', 'contactTime', 'technicianNotes', 'dispatchNotes'],
    essentialFacts: ['customerArrived', 'arrivalStatus'],
    recommendedFacts: ['customerAvailable', 'arrivalTime', 'technicianNotes'],
    impactIds: ['service-unresolved', 'waited-window', 'new-appointment', 'repeated-failed-visits', 'escalation-requested', 'cancellation-risk', 'accessibility-safety', 'dissatisfaction'],
    contradictionRules: ['arrival-mismatch', 'contact-mismatch'],
    emailSentenceIntents: ['customer-arrival', 'record-arrival'],
    reviewAreas: ['arrival activity', 'arrival timestamps', 'technician notes', 'dispatch notes'],
  },
  {
    id: 'no-work-attempted',
    group: 'Work performed',
    label: 'No work was attempted',
    questionIds: ['workAttempted', 'workCompleted', 'customerInstructions', 'reasonProvided', 'visitStatus', 'completionStatus', 'technicianNotes', 'dispatchNotes'],
    essentialFacts: ['workAttempted', 'completionStatus'],
    recommendedFacts: ['customerInstructions', 'reasonProvided', 'technicianNotes'],
    impactIds: ['service-unresolved', 'new-appointment', 'repeat-troubleshooting', 'repeated-failed-visits', 'escalation-requested', 'cancellation-risk', 'accessibility-safety', 'dissatisfaction'],
    contradictionRules: ['completion-mismatch'],
    emailSentenceIntents: ['customer-work', 'record-completion'],
    reviewAreas: ['work performed', 'completion coding', 'technician notes'],
  },
  {
    id: 'work-not-completed',
    group: 'Work performed',
    label: 'Work was not completed',
    questionIds: ['workAttempted', 'workCompleted', 'customerInstructions', 'reasonProvided', 'visitStatus', 'completionStatus', 'technicianNotes', 'dispatchNotes'],
    essentialFacts: ['workCompleted', 'completionStatus'],
    recommendedFacts: ['workAttempted', 'reasonProvided', 'technicianNotes'],
    impactIds: ['service-unresolved', 'new-appointment', 'repeat-troubleshooting', 'repeated-failed-visits', 'escalation-requested', 'cancellation-risk', 'accessibility-safety', 'dissatisfaction'],
    contradictionRules: ['completion-mismatch'],
    emailSentenceIntents: ['customer-work', 'record-completion'],
    reviewAreas: ['work performed', 'unresolved scope', 'completion coding', 'technician notes'],
  },
  {
    id: 'left-before-resolution',
    group: 'Work performed',
    label: 'Technician left before resolution',
    questionIds: ['workAttempted', 'workCompleted', 'customerInstructions', 'reasonProvided', 'visitStatus', 'completionStatus', 'technicianNotes', 'dispatchNotes'],
    essentialFacts: ['workCompleted'],
    recommendedFacts: ['workAttempted', 'reasonProvided', 'completionStatus', 'technicianNotes'],
    impactIds: ['service-unresolved', 'new-appointment', 'repeat-troubleshooting', 'repeated-failed-visits', 'escalation-requested', 'cancellation-risk', 'accessibility-safety', 'dissatisfaction'],
    contradictionRules: ['completion-mismatch'],
    emailSentenceIntents: ['customer-work', 'record-completion'],
    reviewAreas: ['visit handling', 'work performed', 'unresolved scope', 'technician notes'],
  },
  {
    id: 'told-contact-support',
    group: 'Customer instructions',
    label: 'Customer was told to contact support or reschedule',
    questionIds: ['contactReceived', 'workAttempted', 'workCompleted', 'customerInstructions', 'instructionType', 'instructionDelivery', 'reasonProvided', 'visitStatus', 'completionStatus', 'technicianNotes', 'dispatchNotes'],
    essentialFacts: ['customerInstructions'],
    recommendedFacts: ['instructionType', 'instructionDelivery', 'reasonProvided', 'workAttempted', 'completionStatus', 'technicianNotes'],
    impactIds: ['service-unresolved', 'redirected-support', 'new-appointment', 'repeat-troubleshooting', 'repeated-failed-visits', 'escalation-requested', 'cancellation-risk', 'accessibility-safety', 'dissatisfaction'],
    contradictionRules: ['completion-mismatch'],
    emailSentenceIntents: ['customer-guidance', 'record-completion'],
    reviewAreas: ['guidance provided', 'appointment ownership', 'technician notes', 'customer recovery'],
  },
  {
    id: 'incorrect-guidance',
    group: 'Customer instructions',
    label: 'Incorrect or unclear guidance was provided',
    questionIds: ['contactReceived', 'customerInstructions', 'instructionType', 'instructionDelivery', 'reasonProvided', 'workAttempted', 'workCompleted', 'technicianNotes', 'dispatchNotes', 'otherInternalInfo'],
    essentialFacts: ['customerInstructions'],
    recommendedFacts: ['instructionType', 'instructionDelivery', 'reasonProvided', 'technicianNotes', 'otherInternalInfo'],
    impactIds: ['service-unresolved', 'redirected-support', 'new-appointment', 'repeat-troubleshooting', 'repeated-failed-visits', 'escalation-requested', 'cancellation-risk', 'accessibility-safety', 'dissatisfaction'],
    contradictionRules: [],
    emailSentenceIntents: ['customer-guidance', 'record-notes'],
    reviewAreas: ['guidance provided', 'appropriate next steps', 'technician notes'],
  },
  {
    id: 'sla-expired',
    group: 'SLA & follow-up',
    label: 'Promised SLA expired — no update',
    questionIds: ['slaDuration', 'customSlaDuration', 'slaCommunicatedAt', 'slaReference', 'slaDueAt', 'slaLastStatus'],
    essentialFacts: ['slaDuration'],
    recommendedFacts: ['slaCommunicatedAt', 'slaReference', 'slaDueAt', 'slaLastStatus'],
    impactIds: ['service-unresolved', 'repeat-troubleshooting', 'repeated-failed-visits', 'escalation-requested', 'cancellation-risk', 'dissatisfaction', 'other'],
    contradictionRules: [],
    emailSentenceIntents: ['sla-promise', 'sla-expired', 'sla-status'],
    reviewAreas: ['expired SLA', 'current case status', 'appropriate resolution'],
  },
  {
    id: 'professional-conduct',
    group: 'Other',
    label: 'Professional-conduct concern',
    questionIds: ['customerAdditional', 'technicianNotes', 'dispatchNotes', 'otherInternalInfo'],
    essentialFacts: ['customerAdditional'],
    recommendedFacts: ['technicianNotes', 'dispatchNotes'],
    impactIds: ['service-unresolved', 'repeated-failed-visits', 'escalation-requested', 'cancellation-risk', 'accessibility-safety', 'dissatisfaction', 'other'],
    contradictionRules: [],
    emailSentenceIntents: ['customer-additional', 'record-notes'],
    reviewAreas: ['professional handling', 'technician notes', 'dispatch information'],
  },
  {
    id: 'other-handling',
    group: 'Other',
    label: 'Other visit-handling concern',
    questionIds: ['customerAdditional', 'technicianNotes', 'dispatchNotes', 'otherInternalInfo'],
    essentialFacts: ['customerAdditional'],
    recommendedFacts: ['otherInternalInfo'],
    impactIds: IMPACTS.map(({ id }) => id),
    contradictionRules: [],
    emailSentenceIntents: ['customer-additional', 'record-notes'],
    reviewAreas: ['visit handling', 'available notes', 'appropriate resolution'],
  },
];

export const SITUATION_BY_ID = Object.fromEntries(SITUATIONS.map((situation) => [situation.id, situation]));

export const SITUATION_GROUPS = ['Arrival', 'Work performed', 'Customer instructions', 'SLA & follow-up', 'Other'];
